# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

#spark.sql("USE CATALOG `<my-catalog>`")
spark.sql("USE SCHEMA `bookstore_etl_pro`")

# COMMAND ----------

display(spark.sql("SELECT count(*) FROM bronze"))
